import 'data_format.dart';

class CategoryData {
  // List<CategoryTemplate> categorydata = [
  //   CategoryTemplate(
  //     id: 0,
  //     category: 'Artist',
  //     subcategory: ['Male Artist', 'Female Artist'],
  //   ),
  //   CategoryTemplate(
  //     id: 1,
  //     category: 'Director',
  //     subcategory: ['Male Director', 'Female Director'],
  //   ),
  // ];
}

class Data {
  // List<DataTemplate> data = [
  //   //Artist
  //   DataTemplate(
  //     id: 1,
  //     name: 'Ali',
  //     category: 'Artist',
  //     subcategory: 'Male Artist',
  //     address: 'Andheri',
  //     phonenumber: '+918850283086',
  //     email: 'alisolanki@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 2,
  //     name: 'Manan',
  //     category: 'Artist',
  //     subcategory: 'Male Artist',
  //     address: 'Ghatkopar',
  //     phonenumber: '+911234567888',
  //     email: 'manan@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 3,
  //     name: 'Ali',
  //     category: 'Artist',
  //     subcategory: 'Male Artist',
  //     address: 'Andheri',
  //     phonenumber: '+917663829090',
  //     email: 'alisolanki@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 4,
  //     name: 'Nishita',
  //     category: 'Artist',
  //     subcategory: 'Female Artist',
  //     address: 'Thane',
  //     phonenumber: '+91766382909202',
  //     email: 'nishit@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 5,
  //     name: 'Ali',
  //     category: 'Artist',
  //     subcategory: 'Male Artist',
  //     address: 'Andheri',
  //     phonenumber: '+91766382909202',
  //     email: 'alisolanki@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 6,
  //     name: 'Manan',
  //     category: 'Artist',
  //     subcategory: 'Male Artist',
  //     address: 'Ghatkopar',
  //     phonenumber: '+91766382909202',
  //     email: 'manan@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 7,
  //     name: 'Ali',
  //     category: 'Artist',
  //     subcategory: 'Male Artist',
  //     address: 'Andheri',
  //     phonenumber: '+91766382909202',
  //     email: 'alisolanki@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 8,
  //     name: 'Nishita',
  //     category: 'Artist',
  //     subcategory: 'Female Artist',
  //     address: 'Thane',
  //     phonenumber: '+91766382909202',
  //     email: 'nishit@gmail.com',
  //   ),
  //   //Director
  //   DataTemplate(
  //     id: 9,
  //     name: 'Ali',
  //     category: 'Artist',
  //     subcategory: 'Male Artist',
  //     address: 'Andheri',
  //     phonenumber: '+91766382909202',
  //     email: 'alisolanki@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 10,
  //     name: 'Manan',
  //     category: 'Artist',
  //     subcategory: 'Male Artist',
  //     address: 'Ghatkopar',
  //     phonenumber: '+91766382909202',
  //     email: 'manan@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 11,
  //     name: 'Ali',
  //     category: 'Artist',
  //     subcategory: 'Male Artist',
  //     address: 'Andheri',
  //     phonenumber: '+91766382909202',
  //     email: 'alisolanki@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 12,
  //     name: 'Nishita',
  //     category: 'Director',
  //     subcategory: 'Female Director',
  //     address: 'Thane',
  //     phonenumber: '+91766382909202',
  //     email: 'nishit@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 13,
  //     name: 'Ali',
  //     category: 'Director',
  //     subcategory: 'Male Director',
  //     address: 'Andheri',
  //     phonenumber: '+91766382909202',
  //     email: 'alisolanki@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 14,
  //     name: 'Manan',
  //     category: 'Director',
  //     subcategory: 'Male Director',
  //     address: 'Ghatkopar',
  //     phonenumber: '+91766382909202',
  //     email: 'manan@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 15,
  //     name: 'Ali',
  //     category: 'Director',
  //     subcategory: 'Male Director',
  //     address: 'Andheri',
  //     phonenumber: '+91766382909202',
  //     email: 'alisolanki@gmail.com',
  //   ),
  //   DataTemplate(
  //     id: 16,
  //     name: 'Nishita',
  //     category: 'Director',
  //     subcategory: 'Female Director',
  //     address: 'Thane',
  //     phonenumber: '+91766382909202',
  //     email: 'nishit@gmail.com',
  //   ),
  // ];
}